# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST https://localhost:5050/products
Content-Type: application/json
{
  "Name": "New Product A",
  "Category": ["c1", "c2"],
  "Description": "Description Prouct A",
  "ImageFile": "ImageFile Product A",
  "Price": 199
}


### Get Products
GET https://localhost:5050/products
Content-Type: application/json

### Get Product By Id
GET https://localhost:5050/products/0190ffe5-684c-4f35-9d6b-3c14cc34126d
Content-Type: application/json
