# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=5051
@url=https://{{hostname}}:{{port}}

# Get basket
GET {{url}}/basket/dgmodesto
Content-Type: application/json


### Create Basket
POST {{url}}/basket
Content-Type: application/json
{
	"Cart": 
        {
            "UserName": "dgmodesto",
            "Items": [
                {
                "Quantity": 2,
                "Color": "Red",
                "Price": 500,
                "ProductId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
                "ProductName": "IPhone X"
                },
                {
                "Quantity": 1,
                "Color": "Blue",
                "Price": 500,
                "ProductId": "c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914",
                "ProductName": "Samsung 10"
                }
            ]  
        }
}

### Delete Basket
DELETE {{url}}/basket/dgmodesto
Content-Type: application/json


### Health Check
GET {{url}}/health
Content-Type: application/json